"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const alunoController_1 = require("./alunos/alunoController");
const cursoController_1 = require("./cursos/cursoController");
const app = (0, express_1.default)();
app.use(express_1.default.json());
app.get('/tabelaAluno', alunoController_1.CriarTabelaAluno);
app.post('/CriarAluno', alunoController_1.CriarAluno);
app.get('/ListarAluno', alunoController_1.ListarAlunosSemCursos);
app.get('/VisualizarAluno/:id', alunoController_1.VisualizarAluno);
app.put('/EditarAluno/:id', alunoController_1.EditarAluno);
app.delete('/DeletarAluno/:id', alunoController_1.DeletarAluno);
app.get('/tabelaCurso', cursoController_1.CriarTabelaCurso);
app.post('/CriarCurso', cursoController_1.CriarCurso);
app.get('/ListarCurso', cursoController_1.ListarCursos);
app.get('/VisualizarCurso/:id', cursoController_1.VisualizarCurso);
app.put('/EditarCurso/:id', cursoController_1.EditarCurso);
app.delete('/DeletarCurso/:id', cursoController_1.DeletarCurso);
app.listen(3000, () => console.log(`Servidor na porta: ${3000}`));
//# sourceMappingURL=server.js.map