### Listar Tudo
GET http://localhost:4000/listarAlunos

### Listar Nomes
GET http://localhost:4000/listarNomesAlunos


### Criar
POST http://localhost:4000/criarAluno
Content-Type: application/json

{
  "nome": "joao",
  "matricula": "777",
  "curso": ["ti","arroz"]
}

### Atualizar
PUT http://localhost:4000/editarAluno/f451fa1c-3076-416c-9821-1db30a9fc59b
Content-Type: application/json

{
  "nome": "aaaaaaaa",
  "curso": "biologia avançada"
}

### Deletar
DELETE http://localhost:4000/deletarAluno/d87311aa-fa14-450a-bc38-75140a356de7