### Listar Tudo
GET http://localhost:4000/listarAlunos

### Listar Nomes
GET http://localhost:4000/listarAluno/c21494b7-9989-4752-a655-d6b1f6b2d24f


### Criar
POST http://localhost:4000/criarAluno
Content-Type: application/json

{
  "nome": "joao",
  "matricula": "777",
  "curso": ["ti","arroz"]
}

### Atualizar Patch
PATCH http://localhost:4000/editarAluno/ead23ad7-7357-4d02-898b-6e3abc67ee93
Content-Type: application/json

{
  "nome": "aaaaaaaa",
  "curso": "biologia avançada"
}

### Atualizar Put
PUT http://localhost:4000/editarAluno/ead23ad7-7357-4d02-898b-6e3abc67ee93
Content-Type: application/json

{
  "nome": "aaaaaaaa",
  "curso": "biologia avançada"
}

### Deletar
DELETE http://localhost:4000/deletarAluno/c21494b7-9989-4752-a655-d6b1f6b2d24f