version: "3.9"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: root
      POSTGRES_DB: apisequelize
    ports:
      - "15432:5432"

  app-sequelize:
    image: apisequelize
    ports:
      - "4000:4000"